db:
  build: ./postgres
  volumes:
    - ./data/postgres:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: odoo
    POSTGRES_PASSWORD: odoo


odoo:
  build: ./
  links:
    - db
  ports:
    - '8069:8069'
